detectors:
  - class: ResNetDetector
    args:
      name: 'Roop Detector - ResNet'
      cfg_path: 'configs/inference/double_head_resnet_fafi_hybrid.yml'
  - class: ViTDetector
    args:
      name: 'Roop Detector - ViT'
      cfg_path: 'configs/inference/double_head_vit_fafi_hybrid.yml'
    
