detectors:
  - class: ResNetDetector
    args:
      name: 'Roop Detector - ResNet - FAFI'
      cfg_path: 'configs/inference/double_head_resnet_fafi_hybrid.yml'
  - class: ResNetDetector
    args:
      name: 'Roop Detector - ResNet - MSR'
      cfg_path: 'configs/inference/double_head_resnet_msr_hybrid.yml'
  - class: ViTDetector
    args:
      name: 'Roop Detector - ViT - FAFI'
      cfg_path: 'configs/inference/double_head_vit_fafi_hybrid.yml'
  - class: ViTDetector
    args:
      name: 'Roop Detector - ViT - MSR'
      cfg_path: 'configs/inference/double_head_vit_msr_hybrid.yml'
  - class: MobileNetDetector
    args:
      name: 'Roop Detector - MobileNet - FAFI'
      cfg_path: 'configs/inference/double_head_mobilenet_fafi_hybrid.yml'
  - class: MobileNetDetector
    args:
      name: 'Roop Detector - MobileNet - MSR'
      cfg_path: 'configs/inference/double_head_mobilenet_msr_hybrid.yml'
    
