detectors:
  - class: ResNetDetector
    args:
      name: 'Generic Landmark (accurate)'
      cfg_path: 'configs/inference/double_head_resnet_fafi_hybrid.yml'
  - class: ViTDetector
    args:
      name: 'Generic Landmark (detail)'
      cfg_path: 'configs/inference/double_head_vit_fafi_hybrid.yml'
  - class: MobileNetDetector
    args:
      name: 'Generic Landmark (lightweight)'
      cfg_path: 'configs/inference/double_head_mobilenet_fafi_hybrid.yml'
  - class: ResNetDetector
    args:
      name: 'Generic Reflectance (accurate)'
      cfg_path: 'configs/inference/double_head_resnet_msr_hybrid.yml'
  - class: ViTDetector
    args:
      name: 'Generic Reflectance (detail)'
      cfg_path: 'configs/inference/double_head_vit_msr_hybrid.yml'
  - class: MobileNetDetector
    args:
      name: 'Generic Reflectance (lightweight)'
      cfg_path: 'configs/inference/double_head_mobilenet_msr_hybrid.yml'
  # - class: ViTDetector
  #   args:
  #     name: 'ViT truncated - FAFI model'
  #     cfg_path: 'configs/inference/double_head_vit_fafi_hybrid.yml'
    
