global:
  username: rainbow-dango
  project_name: hcmus-fsd
  run_name: distill-single-vit224-mobilenetv3
  save_dir: logs
  SEED: 47
  resume: Null
dataset:
  name: FaceSpoofingDataset
  transform:
    train: train_classify_tf
    val: test_classify_tf
    test: test_classify_tf
  args:
    train:
      source_path: fsd-deepfakerapp/deepfaker_app/face_crop/train
      split_file: all.csv
      oversampling: True
    val:
      source_path: fsd-deepfakerapp/deepfaker_app/face_crop/test
      split_file: all.csv
      oversampling: False
    test:
      source_path: fsd-deepfakerapp/deepfaker_app/face_crop/test
      split_file: all.csv
      oversampling: False
data_loader:
  train:
    args:
      batch_size: 64
      num_workers: 8
      shuffle: True
  val:
    args:
      batch_size: 64
      num_workers: 8
      shuffle: False
  test:
    args:
      batch_size: 64
      num_workers: 8
      shuffle: False
model:
  name: DistillationFrameClassifier
  input_size: 224
  num_classes: 2
  extractor:
    img_encoder:
      name: MobileNetExtractor
      args:
        version: mobilenetv3_large_100
        from_pretrained: True
        freeze: False
  teacher_config:
    teacher_config_file: logs/vit94/config.yaml
    config_type: wandb
    weight_path: logs/vit94/iypqhuou/checkpoints/singleVit224-epoch=25-val_acc=0.9478.ckpt
    temperature: 1.5
  alpha: 0.9
metric:
  - name: Accuracy
    args:
  - name: BinaryEqualErrorRate
    args:
trainer:
  num_worker: 8
  start_epoch: 0
  start_epoch: 0
  num_epochs: 100
  evaluate_interval: 1
  log_interval: 20
  use_fp16: True
  debug: False
optimizer:
  lr: 0.0001
lr_scheduler:
  name: ReduceLROnPlateau
  args:
    mode: min
    factor: 0.5
    patience: 3
    min_lr: 0.00001
  monitor: val/loss
callbacks:
  - name: ModelCheckpoint
    args:
      filename: "singleVit224-epoch={epoch}-val_acc={val/accuracy:.4f}"
      monitor: "val/accuracy"
      verbose: True
      save_top_k: 3
      mode: max
      auto_insert_metric_name: False #https://github.com/Lightning-AI/lightning/issues/4012
  - name: EarlyStopping
    args:
      monitor: "val/loss"
      min_delta: 0.0001
      patience: 5
      verbose: False
      mode: min
  - name: LearningRateMonitor
    args:
      logging_interval: step
      



