global:
  username: rainbow-dango
  project_name: hcmus-fsd
  run_name: double-shared-vit_tiny_patch16_224-newdataset
  save_dir: logs
  SEED: 47
  resume: null
dataset:
  name: FaceVariantSpoofingDataset
  transform:
    train: train_classify_replay_tf
    val: test_classify_tf
    test: test_classify_tf
  args:
    train:
      source_path: fsd-deepfakerapp/hybrid/train
      split_file: all_50.csv
      oversampling: True
    val:
      source_path: fsd-deepfakerapp/hybrid/val
      split_file: all_50.csv
      oversampling: False
    test:
      source_path: fsd-deepfakerapp/hybrid/test
      split_file: all_100.csv
      oversampling: False
data_loader:
  train:
    args:
      batch_size: 32
      num_workers: 8
      shuffle: True
  val:
    args:
      batch_size: 32
      num_workers: 8
      shuffle: False
  test:
    args:
      batch_size: 32
      num_workers: 8
      shuffle: False
model:
  name: DoubleHeadAttentionFrameClassifier
  input_size: 224
  num_classes: 2
  extractor:
    img_encoder:
      name: VitNetExtractor
      args:
        version: vit_tiny_patch16_224
        from_pretrained: True
        freeze: False
        in_channels: 6 # 3 orginal + 3 variant (landmark, msr)
metric:
  - name: Accuracy
    args:
  - name: BinaryEqualErrorRate
    args:
trainer:
  num_worker: 8
  start_epoch: 0
  start_epoch: 0
  num_epochs: 100
  evaluate_interval: 1
  log_interval: 20
  use_fp16: True
  debug: False
optimizer:
  lr: 0.0001
lr_scheduler:
  name: ReduceLROnPlateau
  args:
    mode: min
    factor: 0.3
    patience: 10
    min_lr: 0.00001
  monitor: val/loss
callbacks:
  - name: ModelCheckpoint
    args:
      filename: "double-shared-vit-epoch={epoch}-val_eer={val/eer:.4f}-val_acc={val/accuracy:.4f}"
      monitor: "val/eer"
      verbose: True
      save_top_k: 3
      mode: min
      auto_insert_metric_name: False #https://github.com/Lightning-AI/lightning/issues/4012
  - name: EarlyStopping
    args:
      monitor: "val/loss"
      min_delta: 0.00001
      patience: 20
      verbose: False
      mode: min
  - name: LearningRateMonitor
    args:
      logging_interval: step
      