dataset:
  data_path: casia-fasd/train
  oversampling: true
  shuffle: true
  train_split: 0.8
data_generator:
  train:
    batch_size: 64
    type_gen: train
    shuffle: true
  val:
    batch_size: 64
    type_gen: val
    shuffle: false
model:
  input_size: 128
  num_classes: 1
  backbone: Xception
  loss: binary_crossentropy
  metrics:
    - accuracy
train:
  num_worker: 8
  start_epoch: 0
  num_epoch: 70
  validate_freq: 1
optimizer:
  learning_rate: 0.0001
  momentum: 0.9

