global:
  username: minhkhoi1026
  project_name: hcmus-fsd
  run_name: casia-fasd
dataset:
  data_path: casia-fasd/train
  oversampling: true
  train_split: 0.8
data_generator:
  train:
    batch_size: 64
    type_gen: train
    shuffle: true
  val:
    batch_size: 64
    type_gen: val
    shuffle: false
model:
  input_size: 128
  num_classes: 1
  backbone: Xception
  loss: binary_crossentropy
  metrics:
    - accuracy
train:
  num_worker: 8
  start_epoch: 0
  num_epoch: 70
  validate_freq: 1
optimizer:
  learning_rate: 0.0001
  momentum: 0.9
callbacks:
  # - name: WandbCallback
  #   params:
  #     monitor: val_accuracy
  #     mode: max
  #     save_model: true
  #     save_weights_only: false
  #     log_best_prefix: "weight-Xception-{epoch:02d}-{accuracy:.2f}-{val_accuracy:.2f}-{val_loss:.5f}"
  - name: CustomModelCheckpoint
    params:
      save_dir: weights/old
      filepath: "weight-Xception-{epoch:02d}-{accuracy:.2f}-{val_accuracy:.2f}-{val_loss:.5f}.hdf5"
      monitor: val_accuracy
      mode: max
      save_best_only: true
      period: 1
      verbose: 1
  - name: WandbMetricsLogger
    params:
      log_freq: epoch
      initial_global_step: 0 # equivalent with train.start_epoch
  - name: EarlyStopping
    params:
      monitor: val_loss
      patience: 5

